apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "usbmuxd.role.fullname" . }}
  labels:
    {{- include "usbmuxd.labels" . | nindent 4 }}
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list" ]
- apiGroups: [ "kaponata.io" ]
  resources: [ "mobiledevices" ]
  verbs: [ "get", "list", "create", "delete" ]
