apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api.ingress.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ include "api.service.fullname" . }}
            port:
              number: 80
