apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "api.role.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
rules:
- apiGroups: [ "kaponata.io" ]
  resources: [ "mobiledevices" ]
  verbs: [ "get", "list" ]
