kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "operator.clusterRoleBinding.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "operator.serviceAccount.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "operator.clusterRole.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
