apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "operator.clusterRole.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
- apiGroups: [ "apiextensions.k8s.io" ]
  resources: [ "customresourcedefinitions" ]
  verbs: [ "get", "list", "watch", "create", "delete" ]
