apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "operator.serviceAccount.fullname" . }}
      containers:
        - name: "operator"
          image: "{{ .Values.operator.image.repository }}:{{ tpl .Values.operator.image.tag . }}"
          imagePullPolicy: "{{ .Values.operator.imagePullPolicy }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/alive
              port: http
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
