apiVersion: v1
kind: Service
metadata:
  name: {{ include "guacamole.guacd.service.fullname" . }}
  labels:
    {{- include "guacamole.guacd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4822
      targetPort: guacd
      protocol: TCP
      name: guacd
  selector:
    {{- include "guacamole.guacd.selectorLabels" . | nindent 4 }}
