apiVersion: v1
kind: Service
metadata:
  name: {{ include "guacamole.guacamole.service.fullname" . }}
  labels:
    {{- include "guacamole.guacamole.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "guacamole.guacamole.selectorLabels" . | nindent 4 }}
