apiVersion: v1
kind: Pod
metadata:
  name: redroid-appium
spec:
  containers:
    - name: appium
      image: quay.io/kaponata/appium-android:latest-amd64
      resources:
        limits:
          memory: "2Gi"
          cpu: "1"
      args: [ "/app/appium/build/lib/main.js" ]
    - name: adb
      image: quay.io/kaponata/appium-android:latest-amd64
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      command: [ "/bin/tini", "--", "/android/platform-tools/adb" ]
      args: [ "-a", "-P", "5037", "server", "nodaemon" ]
  nodeSelector:
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux
