apiVersion: v1
kind: Pod
metadata:
  name: redroid
  labels:
    kubernetes.io/arch: amd64
    kubernetes.io/os: android
spec:
  containers:
    - name: android
      image: redroid/redroid:11.0.0-latest
      securityContext:
        privileged: true
      env:
      - name: redroid.vncserver
        value: "1"
      ports:
        - name: vnc
          containerPort: 5900
          protocol: TCP
        - name: adbd
          containerPort: 5555
          protocol: TCP
      readinessProbe:
        exec:
          command:
            - "sh"
            - "-c"
            - '[ "$(getprop init.svc.bootanim)x" == "stoppedx" ]'
        initialDelaySeconds: 5
        periodSeconds: 5
      resources:
        limits:
          memory: "2Gi"
          cpu: "1"
  nodeSelector:
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux
