name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: dotnet/nbgv@v0.4.0
        id: nbgv
        with:
          path: src

      - name: Provision CI environment
        run: |
          ansible-galaxy install geerlingguy.docker
          ansible-galaxy install geerlingguy.nodejs
          ansible-galaxy install andrewrothstein.k3d
          ansible-galaxy install andrewrothstein.kubectl
          ansible-galaxy install andrewrothstein.kubernetes-helm
          ansible-galaxy install andrewrothstein.yq

          # Delete files which may cause conflicts
          sudo rm /usr/local/bin/kubectl

          ansible-playbook --version
          ansible-playbook --connection=local --inventory "127.0.0.1," -e 'ansible_python_interpreter=/usr/bin/python3' ci/playbook.yml

      - name: Test operator
        run: >
          dotnet test
          --results-directory ${{ github.workspace }}/bin/Kaponata.TestResults/
          --collect:"XPlat Code Coverage"
          --logger "junit;LogFileName=${{ github.workspace }}/bin/operator-{assembly}.TestResults.xml"
          --filter "TestCategory!=IntegrationTest"
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
        working-directory: src/

      - name: Generate Code Coverage Report
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.4
        with:
          reports: ${{ github.workspace }}/bin/Kaponata.TestResults/**/coverage.cobertura.xml
          targetdir: ${{ github.workspace }}/bin/Kaponata.coveragereport/${{ github.ref }}/
          reporttypes: 'HtmlInline;Cobertura'
        
      - name: Publish Operator Coverage Summary
        uses: 5monkeys/cobertura-action@master
        if: always()
        with:
          path:  ${{ github.workspace }}/bin/Kaponata.coveragereport/${{ github.ref }}/Cobertura.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 75

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coveragereport
          path: ${{ github.workspace }}/bin/${{ github.ref }}/Kaponata.coveragereport

      - name: Publish Operator Coverage Summary to CI website
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: ${{ github.workspace }}/bin/Kaponata.coveragereport/
          container_name: '$web'
          connection_string: ${{ secrets.CiStorageConnectionString }}
          sync: false

      - name: Find Code Coverage Comment
        uses: peter-evans/find-comment@v1
        if: ${{ github.event_name == 'pull_request' }}
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: The code coverage report for this pull request

      - name: Create Code Coverage Comment
        if: ${{ github.event_name == 'pull_request' && steps.fc.outputs.comment-id == 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The code coverage report for this pull request [is available online](https://ci.kaponata.io/${{ github.ref }}/index.html)

      - name: Package operator
        run: |
          set -e

          dotnet publish -c Release
          make
        working-directory: src/Kaponata.Operator/

      - name: Package UI
        run: |
          set -e
          export PATH="$PATH:/usr/local/lib/npm/bin/"

          npm install
          ng build --prod
          make
        working-directory: src/kaponata-ui/

      - name: Create Helm chart
        run: |
          set -e

          yq e '.version="${{ steps.nbgv.outputs.SemVer2 }}"' -i Chart.yaml
          yq e '.appVersion="${{ steps.nbgv.outputs.SemVer2 }}"' -i Chart.yaml

          helm lint .
          helm package . -d ${{ github.workspace }}/bin
        working-directory: src/chart

      - name: Upload Helm chart
        uses: actions/upload-artifact@v2
        with:
          name: chart
          path: |
            ${{ github.workspace }}/bin/

      - name: Create k3d cluster
        run: |
          set -e

          k3d cluster create --api-port 6433 -p "80:80@loadbalancer"

      - name: Deploy Helm chart
        run: >
          helm install
          --wait
          kaponata ${{ github.workspace }}/bin/kaponata-${{ steps.nbgv.outputs.SemVer2 }}.tgz

      - name: Run chart tests and integration tests
        run: >
          dotnet test
          --logger "junit;LogFileName=${{ github.workspace }}/bin/chart-{assembly}.TestResults.xml"
          --filter "TestCategory=IntegrationTest"
        working-directory: src/

      - name: Delete k3d cluster
        run: |
          set -e

          k3d cluster delete

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "bin/*.TestResults.xml"

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: |
            ${{ github.workspace }}/bin/Kaponata.TestResults/
