name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04	
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: dotnet/nbgv@v0.4.0
        id: nbgv
        with:
          path: src

      - name: Provision CI environment
        run: |
          ansible-galaxy install geerlingguy.docker
          ansible-galaxy install andrewrothstein.k3d
          ansible-galaxy install andrewrothstein.kubectl
          ansible-galaxy install andrewrothstein.kubernetes-helm
          ansible-galaxy install andrewrothstein.yq

          # Delete files which may cause conflicts
          sudo rm /usr/local/bin/kubectl

          ansible-playbook --version
          ansible-playbook --connection=local --inventory "127.0.0.1," -e 'ansible_python_interpreter=/usr/bin/python3' ci/playbook.yml

      - name: Build operator
        run: |
          set -e

          dotnet build -c Release
        working-directory: src/

      - name: Package operator
        run: |
          set -e

          dotnet publish -c Release
          make
        working-directory: src/Kaponata.Operator/

      - name: Create Helm chart
        run: |
          set -e

          yq e '.version="${{ steps.nbgv.outputs.SemVer2 }}"' -i Chart.yaml
          yq e '.appVersion="${{ steps.nbgv.outputs.SemVer2 }}"' -i Chart.yaml

          helm lint .
          helm package . -d ${{ github.workspace }}/bin
        working-directory: src/chart

      - name: Upload Helm chart
        uses: actions/upload-artifact@v2
        with:
          name: chart
          path: |
            ${{ github.workspace }}/bin/

      - name: Create k3d cluster
        run: |
          set -e

          k3d cluster create --api-port 6433 -p "80:80@loadbalancer"

      - name: Deploy Helm chart
        run: |
          set -e

          helm install kaponata ${{ github.workspace }}/bin/kaponata-${{ steps.nbgv.outputs.SemVer2 }}.tgz

      - name: Delete k3d cluster
        run: |
          set -e

          k3d cluster delete
