name: copilot
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java (CoPilot)
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Upload to CoPilot
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
