name: early-feedback
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_container:
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0.202-${{ matrix.container }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            container: focal

          - os: ubuntu-20.04
            container: alpine3.13

          - os: ubuntu-20.04
            container: buster-slim

          - os: ubuntu-20.04
            container: focal

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build in release mode
        run: dotnet build -c Release
        working-directory: src/

      - name: Test
        run: >
          dotnet test
          --results-directory ${{ github.workspace }}/bin/${{ matrix.container }}/Kaponata.TestResults/
          --collect:"XPlat Code Coverage"
          --logger "junit;LogFileName=${{ github.workspace }}/bin/${{ matrix.container }}/{assembly}.TestResults.xml"
          --logger "trx"
          --filter "TestCategory!=IntegrationTest"
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
        working-directory: src/

      - name: Upload Code Coverage Report, Test Results
        uses: actions/upload-artifact@v2
        with:
          name: coveragereport
          path: ${{ github.workspace }}/bin/

  build_native:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-10.15
          
          - os: windows-2019

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build in release mode
        run: dotnet build -c Release
        working-directory: src/

      - name: Test
        run: >
          dotnet test
          --results-directory ${{ github.workspace }}/bin/${{ matrix.os }}/Kaponata.TestResults/
          --collect:"XPlat Code Coverage"
          --logger "junit;LogFileName=${{ github.workspace }}/bin/${{ matrix.os }}/{assembly}.TestResults.xml"
          --logger "trx"
          --filter "TestCategory!=IntegrationTest"
          --
          DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
        working-directory: src/

      - name: Upload Code Coverage Report, Test Results
        uses: actions/upload-artifact@v2
        with:
          name: coveragereport
          path: ${{ github.workspace }}/bin/

  coverage_report:
    needs:
    - build_container
    - build_native

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: coveragereport
          path: ${{ github.workspace }}/bin/

      - name: Generate Code Coverage Report
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.4
        with:
          reports: ${{ github.workspace }}/bin/**/Kaponata.TestResults/**/coverage.cobertura.xml
          targetdir: ${{ github.workspace }}/bin/Kaponata.coveragereport/${{ github.ref }}/coverage/
          reporttypes: 'HtmlInline;Cobertura'

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coveragereport
          path: ${{ github.workspace }}/bin/${{ github.ref }}/Kaponata.coveragereport

      - name: Publish Operator Coverage Summary to CI website
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: ${{ github.workspace }}/bin/Kaponata.coveragereport/
          container_name: '$web'
          connection_string: ${{ secrets.CiStorageConnectionString }}
          sync: false

      - name: Find Code Coverage Comment
        uses: peter-evans/find-comment@v1
        if: ${{ github.event_name == 'pull_request' }}
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: The code coverage report for this pull request

      - name: Create Code Coverage Comment
        if: ${{ github.event_name == 'pull_request' && steps.fc.outputs.comment-id == 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The code coverage report for this pull request [is available online](https://kaponataci.z6.web.core.windows.net/${{ github.ref }}/coverage/index.html)
