name: images
on:
  push:
    branches:
      - main
  pull_request:
    paths:
    - src/iproxy/**
    - src/usbmuxd/**
    - src/adb/**
    - src/fake-driver/**
    - src/appium/**
    - src/appium-android/**

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
        - iproxy
        - usbmuxd
        - adb
        - fake-driver
        - appium
        - appium-android

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: dotnet/nbgv@v0.4.0
        id: nbgv
        with:
          path: src

      - name: Install gomplate
        run: |
          # Install gomplate, used by some Dockerfile templates
          sudo curl -L https://github.com/hairyhenderson/gomplate/releases/download/v3.8.0/gomplate_linux-amd64 -o /usr/local/bin/gomplate -s
          sudo chmod +x /usr/local/bin/gomplate
          gomplate --version

      - name: Build Docker image
        run: make
        working-directory: src/${{ matrix.image }}

      - name: Login to quay.io
        if: github.ref == 'refs/heads/main'
        run: docker login -u="${{ secrets.QUAY_ACCOUNT_NAME }}" -p="${{ secrets.QUAY_ACCOUNT_TOKEN }}" quay.io

      - name: Publish Operator container image
        if: github.ref == 'refs/heads/main'
        run: make push
        working-directory: src/${{ matrix.image }}